<?php

declare(strict_types=1);

namespace Technodelight\Jira\Renderer\Action\Show\Statuses;

use Technodelight\Jira\Renderer\Action\ActionRenderer;
use Technodelight\Jira\Renderer\Action\Result;

class Renderer extends ActionRenderer
{
    public function canProcess(Result $result): bool
    {
        return parent::canProcess($result); // TODO: Change the autogenerated stub
    }

}
