on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '*'

name: Build and Create Release

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-dev -o

    - name: Install box
      run: wget https://github.com/humbug/box/releases/download/4.1.0/box.phar -O box && chmod 0755 box && pwd

    # Runs a single command using the runners shell
    - name: Build phar
      run: ./build --workflow

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      id: upload_artifact
      with:
        name: build
        path: jira.phar

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: Create changelog text
        id: changelog
        uses: loopwerk/tag-changelog@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          exclude_types: other,doc,chore
      - name: Create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.changelog.outputs.changes }}
          draft: true
          prerelease: false
      - name: Upload release asset
        uses: actions/upload-release-asset@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: jira.phar
          asset_name: jira.phar
          asset_content_type: application/php
      - name: Publish release
        uses: StuYarrow/publish-release@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}
